version: '3.7'

services:
  php:
    volumes:
      - ./api:/srv/app
    environment:
      - APP_ENV=dev
      - DATA_DIR=%kernel.project_dir%/data
      - DATABASE_URL=sqlite:///%kernel.project_dir%/data/zippy.db

  nginx:
    volumes:
      - ./api/public:/srv/app/public

  worker:
    volumes:
      - ./api:/srv/app
    environment:
      - APP_ENV=dev
      - DATA_DIR=%kernel.project_dir%/data
      - DATABASE_URL=sqlite:///%kernel.project_dir%/data/zippy.db
