version: '3.7'

networks:
  zippy:

services:
  fpm:
    image: ${DOCKER_REGISTRY}/zippy-api-fpm:$DOCKER_TAG
    build:
      context: ./api
      target: zippy-api-fpm
    networks:
      zippy:
        aliases:
          - zippy-fpm
    environment:
      - APP_ENV
      - DATABASE_URL
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - TRUSTED_PROXIES
    volumes:
      - zippy_vol:/data
    depends_on:
      - rabbitmq

  nginx:
    image: ${DOCKER_REGISTRY}/zippy-api-nginx:$DOCKER_TAG
    build:
      context: ./api
      target: zippy-api-nginx
    networks:
      zippy:
        aliases:
          - zippy-api
    ports:
      - ${ZIPPY_API_PORT}:80
    depends_on:
      - fpm

  worker:
    image: ${DOCKER_REGISTRY}/zippy-worker:$DOCKER_TAG
    build:
      context: ./api
      target: zippy-worker
    networks:
      - zippy
    depends_on:
      - rabbitmq
    environment:
      - APP_ENV
      - DATABASE_URL
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - VERIFY_SSL
    volumes:
      - zippy_vol:/data

  rabbitmq:
    image: rabbitmq:3.7.14-management
    hostname: rabbitmq
    networks:
      - zippy
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq

volumes:
  rabbitmq_vol:
  zippy_vol:
