version: '3.7'

services:
  api:
    volumes:
      - ./api:/srv/app
    environment:
      - APP_ENV=dev
      - DATA_DIR=%kernel.project_dir%/data
      - DATABASE_URL=sqlite:///%kernel.project_dir%/data/zippy.db
      - TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR

  worker:
    volumes:
      - ./api:/srv/app
    environment:
      - APP_ENV=dev
      - DATA_DIR=%kernel.project_dir%/data
      - DATABASE_URL=sqlite:///%kernel.project_dir%/data/zippy.db
