image:
  registry: alchemyfr
  tag: latest

fullnameOverride:
nameOverride:

rabbitmq:
  enabled: true
  username: zippy
  password: defineme
  # Define host only if rabbitmq service is disabled
  host:
  port: 5672
  vhost: /
  externalSecretName:  
  ssl: false
  persistence:
    enabled: true
    existingClaim:
    storageClass:
    annotations: {}
    accessMode: ReadWriteOnce
    size: 1Gi
    subPath:

zippy:
  # You should defined restricted IP.
  # or (/!\ insecured) '127.0.0.1,REMOTE_ADDR' to allow all proxies
  trustedProxies: '127.0.0.1,REMOTE_ADDR'
  database:
    # i.e. postgres://user@pass:port/db-name
    dsn:
  persistence:
    enabled: true
    existingClaim:
    storageClass:
    annotations: {}
    accessMode: ReadWriteOnce
    subPath:
    size: 5Gi

  maxExpirationTime: -1

  storage:
    serveOnS3: false

  client:
    id: client
    secret: secret

  worker:
    replicas: 1

ingress:
  secretName:
  hostname:
