{{ with .Values.zippy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zippy.fullname" $ }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zippy
      tier: api
  template:
    metadata:
      labels:
        app: zippy
        tier: api
    spec:
      volumes:
        - name: data
          {{- if .persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "zippy.fullname" $ }}-data-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
      containers:
      - name: zippy-api
        image: {{ $.Values.image.registry }}/zippy-api:{{ $.Values.image.tag }}
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
          - name: data
            mountPath: "/data"
        env:
          - name: TRUSTED_PROXIES
            value: {{ required "Missing zippy.trustedProxies" .trustedProxies | default "127.0.0.1" | quote }}
          {{- include "zippy.rabbitmqCredentials" $ | indent 10 }}
        envFrom:
          - secretRef:
              name: {{ include "zippy.fullname" $ }}-rabbitmq
          - secretRef:
              name: {{ include "zippy.fullname" $ }}-client-secret
          - secretRef:
              name: {{ include "zippy.fullname" $ }}-db-secret
{{- end }}

