{{- with .Values.rabbitmq }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zippy.fullname" $ }}-rabbitmq
stringData:
  {{- if not (and .externalSecretName .externalSecretMap.username) }}
  RABBITMQ_USER: {{ .username | quote }}
  {{- end }}
  {{- if not (and .externalSecretName .externalSecretMap.password) }}
  RABBITMQ_PASSWORD: {{ .password | quote }}
  {{- end }}
  RABBITMQ_HOST: {{ if .host -}}
  {{- .host | quote -}}
  {{- else -}}
  {{- include "zippy.fullname" $ }}-rabbitmq
  {{- end }}
  RABBITMQ_PORT: {{ .port | quote }}
  RABBITMQ_VHOST: {{ .vhost | quote }}
  RABBITMQ_SSL: {{ .ssl | quote }}
{{- end }}

