{{- with .Values.rabbitmq }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zippy
      tier: rabbitmq
  template:
    metadata:
      labels:
        app: zippy
        tier: rabbitmq
    spec:
      volumes:
      - name: rabbitmq
        {{- if .persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "zippy.fullname" $ }}-rabbitmq-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "rabbitmq"
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.14-management
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: rabbitmq
          mountPath: "/var/lib/rabbitmq"
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "zippy.fullname" $ }}-rabbitmq
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "zippy.fullname" $ }}-rabbitmq
              key: RABBITMQ_PASSWORD
        envFrom:
        - configMapRef:
            name: rabbitmq-config
{{- end }}
{{- end }}
