{{- with .Values.rabbitmq }}
{{- if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zippy.fullname" $ }}-rabbitmq-config
data:
  RABBITMQ_NODENAME: "rabbit@{{ include "zippy.fullname" $ }}-rabbitmq"
  RABBITMQ_ERLANG_COOKIE: "nUhtWhdRmqbhnEYIiwlC"
  ERL_EPMD_PORT: "55950"
{{- end }}
{{- end }}
