{{- with .Values.rabbitmq }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zippy.fullname" $ }}-rabbitmq
stringData:
  RABBITMQ_USER: {{ .username | quote }}
  RABBITMQ_PASSWORD: {{ .password | quote }}
{{- end }}
