apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zippy.fullname" $ }}-php-config
data:
  APP_ENV: prod
  TRUSTED_PROXIES: {{ required "Missing zippy.trusted_proxies" .Values.zippy.trusted_proxies | quote }}
