App\Api\ArchiveInput:
  properties:
    identifier:
      - NotBlank:
          allowNull: true
          groups: [Post]
    files:
      - NotNull: ~
      - Count:
          min: 1
      - Valid: ~

App\Entity\Archive:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: identifier

App\Entity\File:
  properties:
    uri:
      - NotNull: ~
      - NotBlank: ~
    path:
      - NotNull: ~
